core/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
# from users.views import ResetPasswordView

app_name = 'core'

urlpatterns = [

    path('', views.main_dashboard, name='main_dashboard'),
    path('login_user/', views.login_user, name='login_user'),
    path('logout_user/', views.logout_user, name='logout_user'),
    path('forgot_password/', views.forget_password, name='forgot_password'),
    path('login/', views.login_base, name='login'),
    path('change_password/<str:token>/', views.change_password, name='change_password')
    # url(r'^finance_account/$', views.finance_accounts, name='finance_account'),
    # url(r'^branch1/$',views.branch1,name='branch1'),
    # url(r'^get_data/$', views.get_dashboard_data, name='get_data'),
    # url(r'^get_data_finance/$',views.get_finance_account_data, name='finance_data'),
    # url(r'^filter_data/$',views.filter_data,name='filter_data'),
    # url(r'^finance_filter/$',views.finance_filter,name='finance_filter')
]

quotes/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.conf.urls import url
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls'))

]

core/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class React(models.Model):
    name = models.CharField(max_length=30)
    detail = models.CharField(max_length=500)

class Profile(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE)
    forget_password_token=models.CharField(max_length=100)
    created_at=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

core/views.py
from django.shortcuts import render,redirect
from rest_framework.views import APIView
from core.models import Profile
from rest_framework.response import Response
from django.contrib.auth import authenticate, login, logout
from .serializer import *
from django.contrib.auth.models import User
import uuid
from .helpers import send_forgot_password_mail
from django.urls import reverse



# Create your views here.
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin






class ReactView(APIView):
    serializer_class = ReactSerializer

    def get(self, request):
        detail = [{"name": detail.name, "detail": detail.detail}
                  for detail in React.objects.all()]
        return Response(detail)

    def post(self, request):
        serializer = ReactSerializer(data=request.data)
        if serializer.is_valid(raise_exception=True):
            serializer.save()
            return Response(serializer.data)


def main_dashboard(request):
    if not request.user.is_authenticated:
        return render(request, 'base_site.html')
    else:
        context={}
        return render(request, 'index.html', context)


def login_base(request):
    res = logout(request)
    return render(request,'base_site.html')

def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        print(username,password)
        user = authenticate(username=username, password=password)
        print(user, "user")
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            return render(request, 'base_site.html', {'error_message': 'Invalid login'})

    return render(request, 'index.html')

def change_password(request,token):
    context={}
    # try:
    profile_obj=Profile.objects.filter(forget_password_token=token).first()
    print(profile_obj)
    print(profile_obj.user.id)
    if request.method=='POST':
        new_password=request.POST.get("password1")
        new_password2 = request.POST.get("password2")
        user_id= request.POST.get("user_id")
        if user_id is None:
            request.session['message'] = 'Invalid UserID'
            return redirect(f'/change_password/{token}')
        if new_password!=new_password2:
            request.session['message'] = 'Both Password should be equal'
            return redirect(f'/change_password/{token}')
        user_obj=User.objects.get(id=user_id)
        print(user_obj)
        user_obj.set_password(new_password)
        user_obj.save()
        return redirect('/login')
    context={'user_id':profile_obj.user.id}
    # except Exception as e:
    #     print(e)
    return render(request,'change_password.html',context)


def logout_user(request):
	res=logout(request)
	response=render(request, 'base_site.html')
	return response

def forget_password(request):
    context={'success_message':''}
    # try:
    if request.method=='POST':
        username=request.POST.get("username")
        user_obj=User.objects.filter(username=username).first()
        print(user_obj,"user_obj")
        if user_obj:
            token=str(uuid.uuid4())
            profile_obj, created=Profile.objects.get_or_create(user=user_obj)
            print(profile_obj,"profile_obj")
            profile_obj.forget_password_token=token
            profile_obj.save()
            x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
            if x_forwarded_for:
                ip = x_forwarded_for.split(',')[0]
            else:
                ip = request.META.get('REMOTE_ADDR')
            port=request.META.get('SERVER_PORT', '')
            print(ip,"ip")
            if request.is_secure():
                protocol = 'https'
            else:
                protocol = 'http'
            send_forgot_password_mail(user_obj,token,protocol,ip,port)
            context["success_message"]="An Email link is sent to the registered email for verification, please change the password through the link "
        else:
            return render(request,'forgot_password.html', {'error_message':'Invalid Username'})
    # except Exception as e:
    #     print(e)
    return render(request,'forgot_password.html',context)

core/templates/base_site.html
<!doctype html>
<html lang="en">
  <head>
  	<title>Padmagiri Nagar Association</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	
	<link rel="stylesheet" href="/static/css/style.css">

	</head>
	<body>
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
					<h2 class="heading-section">Padmagiri Nagar Association</h2>
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-md-12 col-lg-10">
					<div class="wrap d-md-flex">
						<div class="img" style="background-image: url(/static/images/houseimage.jpg);">
			      </div>
						<div class="login-wrap p-4 p-md-5">
			      	<div class="d-flex">
			      		<div class="w-100">
			      			<h3 class="mb-4">Sign In</h3>
			      		</div>
								<div class="w-100">
									<p class="social-media d-flex justify-content-end">
										<a href="#" class="social-icon d-flex align-items-center justify-content-center"><span class="fa fa-facebook"></span></a>
										<a href="#" class="social-icon d-flex align-items-center justify-content-center"><span class="fa fa-twitter"></span></a>
									</p>
								</div>
			      	</div>
							<form action="{% url 'core:login_user'%}" class="signin-form" method="POST">
								{% csrf_token %}
								<div style="text-align: center;">
									{% if error_message %}
									<p style="color:red"><strong>{{ error_message }}</strong></p>
									{% endif %}
								</div>
			      		<div class="form-group mb-3">
			      			<label class="label" for="name">Username</label>
			      			<input type="text" name="username" class="form-control" placeholder="Username" required>
			      		</div>
		            <div class="form-group mb-3">
		            	<label class="label" for="password">Password</label>
		              <input type="password" name="password" class="form-control" placeholder="Password" required>
		            </div>
		            <div class="form-group">
		            	<button type="submit" class="form-control btn btn-primary rounded submit px-3">Sign In</button>
		            </div>
		            <div class="form-group d-md-flex">
		            	<div class="w-50 text-left">
			            	<label class="checkbox-wrap checkbox-primary mb-0">Remember Me
									  <input type="checkbox" checked>
									  <span class="checkmark"></span>
										</label>
									</div>
									<div class="w-50 text-md-right">
										<a href="{% url 'core:forgot_password' %}">Forgot Password</a>
									</div>
		            </div>
		          </form>
		        </div>
		      </div>
				</div>
			</div>
		</div>
	</section>

	<script src="/static/js/jquery.min.js"></script>
  <script src="/static/js/popper.js"></script>
  <script src="/static/js/bootstrap.min.js"></script>
  <script src="/static/js/main.js"></script>

	</body>
</html>

core/templates/change_password.html
<!doctype html>
<html lang="en">
  <head>
  	<title>Padmagiri Nagar Association</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

	<link rel="stylesheet" href="/static/css/style.css">

	</head>
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
					<h2 class="heading-section">Padmagiri Nagar Phase-2 Welfare Association</h2>
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-md-12 col-lg-10">
					<div class="wrap d-md-flex">
						<div class="img" style="background-image: url(/static/images/spgn2.png);">
			      </div>
						<div class="login-wrap p-4 p-md-5">
			      	<div class="d-flex">
			      		<div class="w-100">
			      			<h3 class="mb-4">Reset Password</h3>
			      		</div>
								<div class="w-100">
									<p class="social-media d-flex justify-content-end">
										<a href="#" class="social-icon d-flex align-items-center justify-content-center"><span class="fa fa-facebook"></span></a>
										<a href="#" class="social-icon d-flex align-items-center justify-content-center"><span class="fa fa-twitter"></span></a>
									</p>
								</div>
			      	</div>
							<form class="signin-form" method="POST">
			      		    {% csrf_token %}
								<div style="text-align: center;">
									{% if request.session.message %}
									<p style="color:red"><strong>{{ request.session.message }}</strong></p>
									{% endif %}
								</div>
<!--								<div class="form-group mb-3">-->
<!--			      			<label class="label" for="email">Email</label>-->
<!--			      			<input type="text" name="username" class="form-control" placeholder="Email" required>-->
<!--			      		</div>-->
		            <div class="form-group mb-3">
		            	<label class="label" for="password1">New Password</label>
		              <input type="password1" class="form-control" placeholder="Enter New Password" name="password1" required>
		            </div>
								<div class="form-group mb-3">
		            	<label class="label" for="password2">Confirm New Password</label>
		              <input type="password2" class="form-control" placeholder="Confirm New Password" name="password2" required>

								</div>
								<input type="hidden" name="user_id" value="{{ user_id }}" />
		            <div class="form-group">
		            	<button type="submit" class="form-control btn btn-primary rounded submit px-3">Confirm</button>
		            </div>
					<p class="text-center"><a href="{% url 'core:login'%}">Back to Login</a></p>
		          </form>
		        </div>
		      </div>
				</div>
			</div>
		</div>
	</section>

	<script src="/static/js/jquery.min.js"></script>
  <script src="/static/js/popper.js"></script>
  <script src="/static/js/bootstrap.min.js"></script>
  <script src="/static/js/main.js"></script>

	</body>
</html>

core/templates/change_password_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Email Template</title>
</head>
<body>
    <h1>Hello user!</h1>

    <p>Click on the link <a href="{{ url }}"> To Change Password</a></p>
</body>
</html>

core/templates/forgot_password.html
<!doctype html>
<html lang="en">
  <head>
  	<title>Padmagiri Nagar Association</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

	<link rel="stylesheet" href="/static/css/style.css">

	</head>
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
					<h2 class="heading-section">Padmagiri Nagar Phase-2 Welfare Association</h2>
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-md-12 col-lg-10">
					<div class="wrap d-md-flex">
						<div class="img" style="background-image: url(/static/images/spgn2.png);">
			      </div>
						<div class="login-wrap p-4 p-md-5">
			      	<div class="d-flex">
			      		<div class="w-100">
			      			<h3 class="mb-4">Reset Password</h3>
			      		</div>
								<div class="w-100">
									<p class="social-media d-flex justify-content-end">
										<a href="#" class="social-icon d-flex align-items-center justify-content-center"><span class="fa fa-facebook"></span></a>
										<a href="#" class="social-icon d-flex align-items-center justify-content-center"><span class="fa fa-twitter"></span></a>
									</p>
								</div>
			      	</div>
							{% if not success_message %}
							<form action="{% url 'core:forgot_password'%}" class="signin-form" method="POST">
			      		    {% csrf_token %}
								<div style="text-align: center;">
									{% if error_message %}
									<p style="color:red"><strong>{{ error_message }}</strong></p>
									{% endif %}
								</div>
								<div class="form-group mb-3">
			      			<label class="label" for="email">Email</label>
			      			<input type="text" name="username" class="form-control" placeholder="Email" required>
			      		</div>
<!--		            <div class="form-group mb-3">-->
<!--		            	<label class="label" for="password">Password</label>-->
<!--		              <input type="password" class="form-control" placeholder="Password" required>-->
<!--		            </div>-->
		            <div class="form-group">
		            	<button type="submit" class="form-control btn btn-primary rounded submit px-3">Generate Email</button>
		            </div>
					<p class="text-center"><a href="{% url 'core:login' %}">Back to Login</a></p>
		          </form>
				  {% elif success_message %}
							<div style="width: 80%;padding: 10px;border: 5px solid gray;margin: 0;">
						<p style="text-align: center"><strong>{{ success_message }}</strong></p>
								</div>
						<p class="text-center"><a href="{% url 'core:login' %}">Back to Login</a></p>
				   {% endif%}
		        </div>
		      </div>
				</div>
			</div>
		</div>
	</section>

	<script src="/static/js/jquery.min.js"></script>
  <script src="/static/js/popper.js"></script>
  <script src="/static/js/bootstrap.min.js"></script>
  <script src="/static/js/main.js"></script>

	</body>
</html>

core/templates/index.html
<h1>HI</h1>